### ISSUE TITLE
Inventory Binder crash...

### ISSUE THREAD

**Issue by therealericbj** [ganymedes01/Gany-s-End#15]
It appears that if I place an Inventory binder block and then return to it later, I get this crash...

http://pastebin.com/cJyw1g5R

A fellow player on my server seems to be also having the same issue...

http://openeye.openmods.info/crashes/12af4fe7134932b139cee54436f8c4b6

For myself, the crash seems to take place as soon as I get back into rendering distance of the block.

Happy Hunting...

**Comment by therealericbj** [comment]
...ooops, sorry...

We are using Forge 1272 and Ganys End-1.8.7.jar

...any other details needed  I'll do my best to get for you...

**Comment by ganymedes01** [comment]
Thanks for report. This was a simple fix :)
