### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by THEVOLCO** [ganymedes01/Gany-s-End#16]
Hi updated some mods and now my game crashes when i Launch it and i think your mod is causing the problem.

Crash Report:

http://pastebin.com/ExBTunHc

**Comment by THEVOLCO** [comment]
Ok, I found out how to fix that bug. I just had to update tinkers

**Comment by ganymedes01** [comment]
Yeah, Gany's End requires an updated version of Tinker's Construct
You can keep using your old version if you want, all you'd have to do is turn off the tinker's construct integration (you can do that in the config file)
