### ISSUE TITLE
Emulator bug with grass

### ISSUE THREAD

**Issue by Neodark7** [ganymedes01/Gany-s-End#18]
http://i.imgur.com/xYgsbqA.png

Forge 10.13.2.1291
Instance with only the three gany's mods
Same on all Biomes

**Comment by ganymedes01** [comment]
Yeah that's an old bug.
Not much I can do about it unfortunately because of the way mojang special cases the grass rendering )=

**Comment by Neodark7** [comment]
huu :( not related to this but small derp :D in the gany's surface config file : "B:"Enable coloured redsotne"=true"
