### ISSUE TITLE
[Feature Suggestion]: Radiant Endium Upgrade

### ISSUE THREAD

**Issue by Lanse505** [ganymedes01/Gany-s-End#22]
Have you gotten tired of your awesome Endium Scythe breaking or your fully enchanted Endium Pickaxe not lasting enough? Well I know i've been in this seat and I thought to myself if only there was a way around this that was more permanent then using a thaumcraft repairer or equivalent.

Now Presenting the new and exciting Radiant Endium Ingot:

Radiant Endium is crafted using 4 Nether Stars and 5 Endium ingots in a TnT Shape.

[E-N-E]
[N-E-N]
[E-N-E]

Output = 4
E = Endium
N = Nether Star

Radiant Endium Ingots can be crafted with any of the normal Endium Tools to "Reinforce" them with the ability to resist Corrosion or Tearing making them virtually indestructable! (outside of dropping them in lava/despawning/voiding/etc) 

I feel this would be a neat feature to have in Gany's End :)

Feel Free to Say No but this is just a suggestion :)

**Comment by ganymedes01** [comment]
I added a Reinforced Ender Scythe to keep more in-line with the other endium tools :)
