### ISSUE TITLE
[Question]: Hey Gany o/

### ISSUE THREAD

**Issue by Lanse505** [ganymedes01/Gany-s-End#23]
Hello Gany :)

We're (RR3 devs) working on finding a wierd chunk loading issue we've been experiencing on one of our test servers. 

Nero [8:31 AM] 
@lanses505 hey if you have like 5(ish) min could u bother ganymede at some point to see if anything in his mods can force chunk load... 

nero [8:36 AM] 
I ran a small inventory test on daves server, since i was noticing that my Indutrial Apiaries were still producing comb even when i was offline

Mind you my home it NOT chunkloaded

lanse505 [8:37 AM] 
couldn't it be pipes ?

nero [8:37 AM] 
no pipes

nero [8:37 AM]
there isn't a single pipe in my home

nero [8:38 AM] 
either BC or LP

nero [8:38 AM]
or anything else that i might be forgetting

So the question is, could there be anything in Surface/Nether/End that would be causing chunks to be force loaded?

(We're looking at other mods also but we're reaching out to everyone involved)

**Comment by GodNero** [comment]
To elaborate a bit farther the ONLY block from any of your mods I have in world is a dual-worktable, I have various others in inventories. I doubt it is yours but as lanse said, we are going with a wide net approach here.

**Comment by ganymedes01** [comment]
The only thing that I can think of that MIGHT cause chunk loading is the Block and Entity Shifters, since to teleport stuff around they'd have to load chunks. But if then, I doubt they'd be keeping chunks loaded constantly (if they are then it's definitely unintentional)
