### ISSUE TITLE
Duplication bug with JABBA barrels and block shifter

### ISSUE THREAD

**Issue by Porcy** [ganymedes01/Gany-s-End#24]
I tried moving a barrel with a block shifter. If there is 1 stack or less in it, it's doing fine. Otherwise, the barrel gets teleported correctly (with all the items inside it) but with dropping/duping all the items but one stack. That does it on every flick of my lever.

**Comment by Porcy** [comment]
That was fast :)

**Comment by ganymedes01** [comment]
Dupe bugs are serious :3
