### ISSUE TITLE
Enchantment list resets once after teleporting the enchantment table with block shifter

### ISSUE THREAD

**Issue by Porcy** [ganymedes01/Gany-s-End#26]
It seems like teleporting an enchantment table with a block shifter resets the enchantments list. This only happens the first time I teleport the table after enchanting something (and thus generating a new list).

**Comment by ganymedes01** [comment]
Do you have the same amount of Bookshelves in the destination as in the origin?

**Comment by Porcy** [comment]
Origin an destination are the same. I actually move the enchantment table out of the way to access a secret room with XP shower and them put it back. But I just got the same bug without moving the table :|
Moving the table seems to guarantee this otherwise random behavior though.

**Comment by ganymedes01** [comment]
Are you using the 1.8 enchanting table (added by Gany's Surface and Et Futurum) or the 1.7.10 one?

**Comment by Porcy** [comment]
The 1.8.

**Comment by ganymedes01** [comment]
Okay, thank you for the information.
I'll look into it and let you know what I find :)

**Comment by Porcy** [comment]
Closing the table's GUI seems to be what causes the reshifting of the enchantments offered. Like: I enchant a book. Without closing the gui I put another book in the enchantment table and it gives me 3 choices. If I then close the GUI and reopen it, 3 new enchants offered.

**Comment by ganymedes01** [comment]
Fixed. The issue was on Et Futurum's side.
